TOC_ENTRIES = [
    {"unit": "Unit 1", "lesson_title": "Measurement", "page": 1},
    {"unit": "Unit 2", "lesson_title": "Force and Pressure", "page": 12},
    {"unit": "Unit 3", "lesson_title": "Light", "page": 22},
    {"unit": "Unit 4", "lesson_title": "Heat", "page": 35},
    {"unit": "Unit 5", "lesson_title": "Electricity", "page": 46},
    {"unit": "Unit 6", "lesson_title": "Sound", "page": 60},
    {"unit": "Unit 7", "lesson_title": "Magnetism", "page": 72},
    {"unit": "Unit 8", "lesson_title": "Universe and Space Science", "page": 83},
    {"unit": "Unit 9", "lesson_title": "Matter around us", "page": 94},
    {"unit": "Unit 10", "lesson_title": "Changes around us", "page": 104},
    {"unit": "Unit 11", "lesson_title": "Air", "page": 114},
    {"unit": "Unit 12", "lesson_title": "Atomic Structure", "page": 124},
    {"unit": "Unit 13", "lesson_title": "Water", "page": 139},
    {"unit": "Unit 14", "lesson_title": "Acids and Bases", "page": 155},
    {"unit": "Unit 15", "lesson_title": "Chemistry in Everyday Life", "page": 166},
    {"unit": "Unit 16", "lesson_title": "Microorganisms", "page": 180},
    {"unit": "Unit 17", "lesson_title": "Plant Kingdom", "page": 192},
    {"unit": "Unit 18", "lesson_title": "Organisation of Life", "page": 205},
    {"unit": "Unit 19", "lesson_title": "Movements in Animals", "page": 218},
    {"unit": "Unit 20", "lesson_title": "Reaching the Age of Adolescence", "page": 232},
    {"unit": "Unit 21", "lesson_title": "Crop Production and Management", "page": 244},
    {"unit": "Unit 22", "lesson_title": "Conservation of Plants and Animals", "page": 260},
    {"unit": "Unit 23", "lesson_title": "Libre Office Calc", "page": 276},
]
